Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,12 +19,12 @@ on:
         type: boolean
         default: false
 
-env:
-  CLUSTER_NAME: Micro-cluster
-
 jobs:
   deploy:
     runs-on: ubuntu-latest
+
+    env:
+      CLUSTER_NAME: Micro-cluster
 
     steps:
     - name: Checkout repository
@@ -119,18 +119,18 @@ jobs:
         
     - name: Create ECS cluster if not exists
       run: |
-        CLUSTER_EXISTS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME --query "clusters[0].status" --output text 2>/dev/null || echo "MISSING")
+        CLUSTER_EXISTS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME --region ${{secrets.AWS_REGION}} --query "clusters[0].status" --output text 2>/dev/null || echo "MISSING")
         
-        if [ "$CLUSTER_EXISTS" = "MISSING" ] || [ "$CLUSTER_EXISTS" = "INACTIVE" ]; then
+        if [ "$CLUSTER_EXISTS" = "MISSING" ] || [ "$CLUSTER_EXISTS" = "INACTIVE" ] || [ "$CLUSTER_EXISTS" = "None" ]; then
           echo "$CLUSTER_NAME Cluster not found. Creating $CLUSTER_NAME ECS cluster..."
-          aws ecs create-cluster --cluster-name $CLUSTER_NAME
+          aws ecs create-cluster --cluster-name $CLUSTER_NAME --region ${{secrets.AWS_REGION}}
         else
           echo "ECS cluster '$CLUSTER_NAME' already exists."
         fi
 
     - name: Launch EC2 instances if none exist
       run: |
-        COUNT=$(aws ecs list-container-instances --cluster $CLUSTER_NAME --query "length(containerInstanceArns)" --output text)
+        COUNT=$(aws ecs list-container-instances --cluster $CLUSTER_NAME --region ${{secrets.AWS_REGION}} --query "length(containerInstanceArns)" --output text)
         if [ "$COUNT" -eq 0 ]; then
           echo "Launching EC2 container instance..."
           AMI_ID=$(aws ssm get-parameters --names /aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id --query "Parameters[0].Value" --output text)
