Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -119,9 +119,8 @@ jobs:
         
     - name: Create ECS cluster if not exists
       run: |
-        CLUSTER_EXISTS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME \
-        --query "clusters[0].status" --output text 2>/dev/null || echo "MISSING")
-
+        CLUSTER_EXISTS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME --query "clusters[0].status" --output text 2>/dev/null || echo "MISSING")
+        
         if [ "$CLUSTER_EXISTS" = "MISSING" ] || [ "$CLUSTER_EXISTS" = "INACTIVE" ]; then
           echo "$CLUSTER_NAME Cluster not found. Creating $CLUSTER_NAME ECS cluster..."
           aws ecs create-cluster --cluster-name $CLUSTER_NAME
