Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -194,5 +194,175 @@ jobs:
           aws ecs update-service --cluster $CLUSTER_NAME --service api-gateway-service --task-definition $TASK_DEF_ARN --force-new-deployment
         fi
 
+        if [ "${{ inputs.deploy_vets }}" = "true" ]; then
+        
+          SERVICE_NAME=vets-service
+          TASK_NAME=vets-task
+        
+          echo "Update and Register Task Definition"
+          
+          sed "s|REPLACE_ME|${{ secrets.ECR_REGISTRY }}/vets-service:${{ env.COMMIT_SHORT_SHA }}|g" ecs-task-definitions/vets-service-task-def.json > final-task-def.json
+          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://final-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
+        
+          echo "Deregistering OLD Task Definition"
+        
+          OLD_REVISIONS=$(aws ecs list-task-definitions --family-prefix $TASK_NAME --status ACTIVE --sort DESC --query 'taskDefinitionArns[1:]' --output text)
 
+          for TD_ARN in $OLD_REVISIONS; do
+            echo "Deregistering $TD_ARN"
+            aws ecs deregister-task-definition --task-definition $TD_ARN
+          done
+        
+          echo "Stop Existing Service Task or Creating New Service"
+        
+          SERVICE_STATUS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" --output text 2>/dev/null || echo "MISSING")
+
+          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
+            echo "Service exists. Checking for running tasks..."
+            TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
+
+            if [ "$TASK_ARN" != "None" ] && [ "$TASK_ARN" != "null" ]; then
+              echo "Stopping task: $TASK_ARN"
+              aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK_ARN
+            else
+              echo "No running tasks found for service."
+            fi
+          else
+            echo "Creating ECS service..."
+            aws ecs create-service --cluster $CLUSTER_NAME --service-name vets-service --task-definition $TASK_DEF_ARN --desired-count 1 --launch-type EC2 --deployment-configuration maximumPercent=200,minimumHealthyPercent=50
+          fi
+        
+          echo "Updating the Service"
+        
+          aws ecs update-service --cluster $CLUSTER_NAME --service api-gateway-service --task-definition $TASK_DEF_ARN --force-new-deployment
+        fi
+
+        if [ "${{ inputs.deploy_customers }}" = "true" ]; then
+        
+          SERVICE_NAME=customers-service
+          TASK_NAME=customers-task
+        
+          echo "Update and Register Task Definition"
+          
+          sed "s|REPLACE_ME|${{ secrets.ECR_REGISTRY }}/customers-service:${{ env.COMMIT_SHORT_SHA }}|g" ecs-task-definitions/customers-service-task-def.json > final-task-def.json
+          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://final-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
+        
+          echo "Deregistering OLD Task Definition"
+        
+          OLD_REVISIONS=$(aws ecs list-task-definitions --family-prefix $TASK_NAME --status ACTIVE --sort DESC --query 'taskDefinitionArns[1:]' --output text)
+
+          for TD_ARN in $OLD_REVISIONS; do
+            echo "Deregistering $TD_ARN"
+            aws ecs deregister-task-definition --task-definition $TD_ARN
+          done
+        
+          echo "Stop Existing Service Task or Creating New Service"
+        
+          SERVICE_STATUS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" --output text 2>/dev/null || echo "MISSING")
+
+          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
+            echo "Service exists. Checking for running tasks..."
+            TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
+
+            if [ "$TASK_ARN" != "None" ] && [ "$TASK_ARN" != "null" ]; then
+              echo "Stopping task: $TASK_ARN"
+              aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK_ARN
+            else
+              echo "No running tasks found for service."
+            fi
+          else
+            echo "Creating ECS service..."
+            aws ecs create-service --cluster $CLUSTER_NAME --service-name customers-service --task-definition $TASK_DEF_ARN --desired-count 1 --launch-type EC2 --deployment-configuration maximumPercent=200,minimumHealthyPercent=50
+          fi
+        
+          echo "Updating the Service"
+        
+          aws ecs update-service --cluster $CLUSTER_NAME --service api-gateway-service --task-definition $TASK_DEF_ARN --force-new-deployment
+        fi
+
+        if [ "${{ inputs.deploy_visits }}" = "true" ]; then
+        
+          SERVICE_NAME=visits-service
+          TASK_NAME=visits-task
+        
+          echo "Update and Register Task Definition"
+          
+          sed "s|REPLACE_ME|${{ secrets.ECR_REGISTRY }}/visits-service:${{ env.COMMIT_SHORT_SHA }}|g" ecs-task-definitions/visits-service-task-def.json > final-task-def.json
+          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://final-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
+        
+          echo "Deregistering OLD Task Definition"
+        
+          OLD_REVISIONS=$(aws ecs list-task-definitions --family-prefix $TASK_NAME --status ACTIVE --sort DESC --query 'taskDefinitionArns[1:]' --output text)
+
+          for TD_ARN in $OLD_REVISIONS; do
+            echo "Deregistering $TD_ARN"
+            aws ecs deregister-task-definition --task-definition $TD_ARN
+          done
+        
+          echo "Stop Existing Service Task or Creating New Service"
+        
+          SERVICE_STATUS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" --output text 2>/dev/null || echo "MISSING")
+
+          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
+            echo "Service exists. Checking for running tasks..."
+            TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
+
+            if [ "$TASK_ARN" != "None" ] && [ "$TASK_ARN" != "null" ]; then
+              echo "Stopping task: $TASK_ARN"
+              aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK_ARN
+            else
+              echo "No running tasks found for service."
+            fi
+          else
+            echo "Creating ECS service..."
+            aws ecs create-service --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --task-definition $TASK_DEF_ARN --desired-count 1 --launch-type EC2 --deployment-configuration maximumPercent=200,minimumHealthyPercent=50
+          fi
+        
+          echo "Updating the Service"
+        
+          aws ecs update-service --cluster $CLUSTER_NAME --service visits-service --task-definition $TASK_DEF_ARN --force-new-deployment
+        fi
+
+        if [ "${{ inputs.deploy_discovery }}" = "true" ]; then
+        
+          SERVICE_NAME=discovery-service
+          TASK_NAME=discovery-task
+        
+          echo "Update and Register Task Definition"
+          
+          sed "s|REPLACE_ME|${{ secrets.ECR_REGISTRY }}/discovery-service:${{ env.COMMIT_SHORT_SHA }}|g" ecs-task-definitions/discovery-service-task-def.json > final-task-def.json
+          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://final-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
+        
+          echo "Deregistering OLD Task Definition"
+        
+          OLD_REVISIONS=$(aws ecs list-task-definitions --family-prefix $TASK_NAME --status ACTIVE --sort DESC --query 'taskDefinitionArns[1:]' --output text)
+
+          for TD_ARN in $OLD_REVISIONS; do
+            echo "Deregistering $TD_ARN"
+            aws ecs deregister-task-definition --task-definition $TD_ARN
+          done
+        
+          echo "Stop Existing Service Task or Creating New Service"
+        
+          SERVICE_STATUS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query "services[0].status" --output text 2>/dev/null || echo "MISSING")
+
+          if [ "$SERVICE_STATUS" == "ACTIVE" ]; then
+            echo "Service exists. Checking for running tasks..."
+            TASK_ARN=$(aws ecs list-tasks --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --query 'taskArns[0]' --output text)
+
+            if [ "$TASK_ARN" != "None" ] && [ "$TASK_ARN" != "null" ]; then
+              echo "Stopping task: $TASK_ARN"
+              aws ecs stop-task --cluster $CLUSTER_NAME --task $TASK_ARN
+            else
+              echo "No running tasks found for service."
+            fi
+          else
+            echo "Creating ECS service..."
+            aws ecs create-service --cluster $CLUSTER_NAME --service-name $SERVICE_NAME --task-definition $TASK_DEF_ARN --desired-count 1 --launch-type EC2 --deployment-configuration maximumPercent=200,minimumHealthyPercent=50
+          fi
+        
+          echo "Updating the Service"
+        
+          aws ecs update-service --cluster $CLUSTER_NAME --service discovery-service --task-definition $TASK_DEF_ARN --force-new-deployment
+        fi
 
